@startuml
left to right direction
:Usuario: as User << Human >>
':Main Database: as MySql << Application >>
':Arduino: as Arduino << Application >>

(Loguear en la app) as (Login)
(Registrarse en la app) as (Registro)
(Recuperar contraseña) as (Recup)

(Manejar luces) as (Luces)
(Manejar calefaccion) as (Calefaccion)
(Manejar persianas) as (Persianas)
(Planificar luces) as (PlanLuces)
(Planificar calefaccion) as (PlanCalefaccion)
(Planificar persianas) as (PlanPersianas)
(Registrar dispositivo) as (Registrar)
(Crear grupo) as (CGrupo)
(Introducir datos de sensores) as (datos)
(Gestionar usuarios) as (usuarios)
(Gestionar grupos) as (grupos)
(Consultardatos de sensores) as (ConsDatos)


User --> (Login)
User --> (Registro)
User --> (Recup)
User --> (Luces)
User --> (PlanLuces)
User --> (Calefaccion)
User --> (PlanCalefaccion)
User --> (Persianas)
User --> (PlanPersianas)
User --> (Registrar)
User --> (CGrupo)
User --> (datos)
User --> (usuarios)
User --> (grupos)
User --> (ConsDatos)
'(Login) <-- MySql
'(Luces) <-- Arduino
'(Calefaccion) <-- Arduino
'(PlanCalefaccion) <-- Arduino
'(PlanLuces) <-- Arduino
'(Persianas) <-- Arduino
'(PlanPersianas) <-- Arduino
@enduml
