"""empty message

Revision ID: 1793c055a33b
Revises: 
Create Date: 2018-04-23 02:02:00.812013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1793c055a33b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dispositivo',
    sa.Column('disID', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('disID')
    )
    op.create_table('Grupo',
    sa.Column('grupoID', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('descripccion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('grupoID')
    )
    op.create_table('Usuario',
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('contraseña', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('nickname')
    )
    op.create_table('Medicion',
    sa.Column('medID', sa.String(length=10), nullable=False),
    sa.Column('disID', sa.String(length=10), nullable=True),
    sa.Column('valor', sa.Float(asdecimal=True), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['disID'], ['Dispositivo.disID'], ),
    sa.PrimaryKeyConstraint('medID')
    )
    op.create_index(op.f('ix_Medicion_disID'), 'Medicion', ['disID'], unique=False)
    op.create_table('ProgramaGrupo',
    sa.Column('progGID', sa.String(length=10), nullable=False),
    sa.Column('grupoID', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('descripccion', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['grupoID'], ['Grupo.grupoID'], ),
    sa.PrimaryKeyConstraint('progGID')
    )
    op.create_index(op.f('ix_ProgramaGrupo_grupoID'), 'ProgramaGrupo', ['grupoID'], unique=False)
    op.create_table('ProgramaIndividual',
    sa.Column('progIID', sa.String(length=10), nullable=False),
    sa.Column('progGID', sa.String(length=10), nullable=True),
    sa.Column('disID', sa.String(length=10), nullable=True),
    sa.Column('valor', sa.Float(asdecimal=True), nullable=False),
    sa.Column('fechaIni', sa.Date(), nullable=False),
    sa.Column('fechaFin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['disID'], ['Dispositivo.disID'], ),
    sa.ForeignKeyConstraint(['progGID'], ['ProgramaGrupo.progGID'], ),
    sa.PrimaryKeyConstraint('progIID')
    )
    op.create_index(op.f('ix_ProgramaIndividual_disID'), 'ProgramaIndividual', ['disID'], unique=False)
    op.create_index(op.f('ix_ProgramaIndividual_progGID'), 'ProgramaIndividual', ['progGID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ProgramaIndividual_progGID'), table_name='ProgramaIndividual')
    op.drop_index(op.f('ix_ProgramaIndividual_disID'), table_name='ProgramaIndividual')
    op.drop_table('ProgramaIndividual')
    op.drop_index(op.f('ix_ProgramaGrupo_grupoID'), table_name='ProgramaGrupo')
    op.drop_table('ProgramaGrupo')
    op.drop_index(op.f('ix_Medicion_disID'), table_name='Medicion')
    op.drop_table('Medicion')
    op.drop_table('Usuario')
    op.drop_table('Grupo')
    op.drop_table('Dispositivo')
    # ### end Alembic commands ###
