"""empty message

Revision ID: 8954744bda64
Revises: 
Create Date: 2018-04-24 15:52:41.604200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8954744bda64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivo',
    sa.Column('disID', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Float(), nullable=False),
    sa.Column('clase', sa.String(length=40), nullable=False),
    sa.Column('funcion', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('disID')
    )
    op.create_table('grupo',
    sa.Column('grupoID', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('descripccion', sa.String(length=200), nullable=True),
    sa.Column('clase', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('grupoID'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('contraseña', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('nickname'),
    sa.UniqueConstraint('email')
    )
    op.create_table('detalleDispositivo',
    sa.Column('grupoID', sa.Integer(), nullable=False),
    sa.Column('disID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disID'], ['dispositivo.disID'], ),
    sa.ForeignKeyConstraint(['grupoID'], ['grupo.grupoID'], ),
    sa.PrimaryKeyConstraint('grupoID', 'disID')
    )
    op.create_index(op.f('ix_detalleDispositivo_disID'), 'detalleDispositivo', ['disID'], unique=False)
    op.create_index(op.f('ix_detalleDispositivo_grupoID'), 'detalleDispositivo', ['grupoID'], unique=False)
    op.create_table('detalleMiembro',
    sa.Column('grupoID', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['grupoID'], ['grupo.grupoID'], ),
    sa.ForeignKeyConstraint(['nickname'], ['usuario.nickname'], ),
    sa.PrimaryKeyConstraint('grupoID', 'nickname')
    )
    op.create_index(op.f('ix_detalleMiembro_grupoID'), 'detalleMiembro', ['grupoID'], unique=False)
    op.create_index(op.f('ix_detalleMiembro_nickname'), 'detalleMiembro', ['nickname'], unique=False)
    op.create_table('medicion',
    sa.Column('medID', sa.Integer(), nullable=False),
    sa.Column('disID', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(asdecimal=True), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['disID'], ['dispositivo.disID'], ),
    sa.PrimaryKeyConstraint('medID')
    )
    op.create_index(op.f('ix_medicion_disID'), 'medicion', ['disID'], unique=False)
    op.create_table('programaGrupo',
    sa.Column('progGID', sa.Integer(), nullable=False),
    sa.Column('grupoID', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('descripccion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['grupoID'], ['grupo.grupoID'], ),
    sa.PrimaryKeyConstraint('progGID')
    )
    op.create_index(op.f('ix_programaGrupo_grupoID'), 'programaGrupo', ['grupoID'], unique=False)
    op.create_table('programaIndividual',
    sa.Column('progIID', sa.Integer(), nullable=False),
    sa.Column('progGID', sa.Integer(), nullable=True),
    sa.Column('disID', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(asdecimal=True), nullable=False),
    sa.Column('fechaIni', sa.Date(), nullable=False),
    sa.Column('fechaFin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['disID'], ['dispositivo.disID'], ),
    sa.ForeignKeyConstraint(['progGID'], ['programaGrupo.progGID'], ),
    sa.PrimaryKeyConstraint('progIID')
    )
    op.create_index(op.f('ix_programaIndividual_disID'), 'programaIndividual', ['disID'], unique=False)
    op.create_index(op.f('ix_programaIndividual_progGID'), 'programaIndividual', ['progGID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programaIndividual_progGID'), table_name='programaIndividual')
    op.drop_index(op.f('ix_programaIndividual_disID'), table_name='programaIndividual')
    op.drop_table('programaIndividual')
    op.drop_index(op.f('ix_programaGrupo_grupoID'), table_name='programaGrupo')
    op.drop_table('programaGrupo')
    op.drop_index(op.f('ix_medicion_disID'), table_name='medicion')
    op.drop_table('medicion')
    op.drop_index(op.f('ix_detalleMiembro_nickname'), table_name='detalleMiembro')
    op.drop_index(op.f('ix_detalleMiembro_grupoID'), table_name='detalleMiembro')
    op.drop_table('detalleMiembro')
    op.drop_index(op.f('ix_detalleDispositivo_grupoID'), table_name='detalleDispositivo')
    op.drop_index(op.f('ix_detalleDispositivo_disID'), table_name='detalleDispositivo')
    op.drop_table('detalleDispositivo')
    op.drop_table('usuario')
    op.drop_table('grupo')
    op.drop_table('dispositivo')
    # ### end Alembic commands ###
