"""empty message

Revision ID: a640dc9cf9b2
Revises: f070cfdaabdc
Create Date: 2018-04-23 18:58:28.634340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a640dc9cf9b2'
down_revision = 'f070cfdaabdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalleDispositivo',
    sa.Column('grupoID', sa.String(length=10), nullable=False),
    sa.Column('disID', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['disID'], ['dispositivo.disID'], ),
    sa.ForeignKeyConstraint(['grupoID'], ['grupo.grupoID'], ),
    sa.PrimaryKeyConstraint('grupoID', 'disID')
    )
    op.create_index(op.f('ix_detalleDispositivo_disID'), 'detalleDispositivo', ['disID'], unique=False)
    op.create_index(op.f('ix_detalleDispositivo_grupoID'), 'detalleDispositivo', ['grupoID'], unique=False)
    op.create_table('detalleMiembro',
    sa.Column('grupoID', sa.String(length=10), nullable=False),
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['grupoID'], ['grupo.grupoID'], ),
    sa.ForeignKeyConstraint(['nickname'], ['usuario.nickname'], ),
    sa.PrimaryKeyConstraint('grupoID', 'nickname')
    )
    op.create_index(op.f('ix_detalleMiembro_grupoID'), 'detalleMiembro', ['grupoID'], unique=False)
    op.create_index(op.f('ix_detalleMiembro_nickname'), 'detalleMiembro', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalleMiembro_nickname'), table_name='detalleMiembro')
    op.drop_index(op.f('ix_detalleMiembro_grupoID'), table_name='detalleMiembro')
    op.drop_table('detalleMiembro')
    op.drop_index(op.f('ix_detalleDispositivo_grupoID'), table_name='detalleDispositivo')
    op.drop_index(op.f('ix_detalleDispositivo_disID'), table_name='detalleDispositivo')
    op.drop_table('detalleDispositivo')
    # ### end Alembic commands ###
