"""empty message

Revision ID: f070cfdaabdc
Revises: 
Create Date: 2018-04-23 18:52:54.949027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f070cfdaabdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivo',
    sa.Column('disID', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('disID')
    )
    op.create_table('grupo',
    sa.Column('grupoID', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('descripccion', sa.String(length=200), nullable=False),
    sa.Column('clase', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('grupoID')
    )
    op.create_table('usuario',
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('contraseña', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('nickname'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medicion',
    sa.Column('medID', sa.String(length=10), nullable=False),
    sa.Column('disID', sa.String(length=10), nullable=True),
    sa.Column('valor', sa.Float(asdecimal=True), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['disID'], ['dispositivo.disID'], ),
    sa.PrimaryKeyConstraint('medID')
    )
    op.create_index(op.f('ix_medicion_disID'), 'medicion', ['disID'], unique=False)
    op.create_table('programaGrupo',
    sa.Column('progGID', sa.String(length=10), nullable=False),
    sa.Column('grupoID', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('descripccion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['grupoID'], ['grupo.grupoID'], ),
    sa.PrimaryKeyConstraint('progGID')
    )
    op.create_index(op.f('ix_programaGrupo_grupoID'), 'programaGrupo', ['grupoID'], unique=False)
    op.create_table('programaIndividual',
    sa.Column('progIID', sa.String(length=10), nullable=False),
    sa.Column('progGID', sa.String(length=10), nullable=True),
    sa.Column('disID', sa.String(length=10), nullable=True),
    sa.Column('valor', sa.Float(asdecimal=True), nullable=False),
    sa.Column('fechaIni', sa.Date(), nullable=False),
    sa.Column('fechaFin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['disID'], ['dispositivo.disID'], ),
    sa.ForeignKeyConstraint(['progGID'], ['programaGrupo.progGID'], ),
    sa.PrimaryKeyConstraint('progIID')
    )
    op.create_index(op.f('ix_programaIndividual_disID'), 'programaIndividual', ['disID'], unique=False)
    op.create_index(op.f('ix_programaIndividual_progGID'), 'programaIndividual', ['progGID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programaIndividual_progGID'), table_name='programaIndividual')
    op.drop_index(op.f('ix_programaIndividual_disID'), table_name='programaIndividual')
    op.drop_table('programaIndividual')
    op.drop_index(op.f('ix_programaGrupo_grupoID'), table_name='programaGrupo')
    op.drop_table('programaGrupo')
    op.drop_index(op.f('ix_medicion_disID'), table_name='medicion')
    op.drop_table('medicion')
    op.drop_table('usuario')
    op.drop_table('grupo')
    op.drop_table('dispositivo')
    # ### end Alembic commands ###
