"""empty message

Revision ID: f78e73cdfeab
Revises: 8954744bda64
Create Date: 2018-04-24 15:53:11.492304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78e73cdfeab'
down_revision = '8954744bda64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nombre', table_name='grupo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('nombre', 'grupo', ['nombre'], unique=True)
    # ### end Alembic commands ###
